name: Build and publish site

on: [push]

jobs:
  build:
    runs-on: [self-hosted, java]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn -q --batch-mode --update-snapshots clean install -Dmaven.javadoc.skip=true -DCI=true -Didea.ignore.disabled.plugins=true -Didea.home.path=/tmp
        working-directory: sitegenerator


